# Generated by Django 5.2.7 on 2025-11-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='articles/thumbnails/%Y/%m/%d/', verbose_name='Миниатюра статьи'),
        ),
    ]
