# Generated by Django 5.2.7 on 2025-11-19 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название жанра')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('color', models.CharField(default='#805AD5', help_text='В формате HEX, например: #805AD5', max_length=7, verbose_name='Цвет жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='genre',
            field=models.ForeignKey(blank=True, help_text="Выберите только если категория 'Игры'", null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.genre', verbose_name='Жанр игры'),
        ),
    ]
