# Generated by Django 5.2.7 on 2025-11-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_genre_article_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='game_developer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Разработчик игры'),
        ),
        migrations.AddField(
            model_name='article',
            name='game_platforms',
            field=models.CharField(blank=True, max_length=300, verbose_name='Платформы (через запятую)'),
        ),
        migrations.AddField(
            model_name='article',
            name='game_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена игры'),
        ),
        migrations.AddField(
            model_name='article',
            name='game_publisher',
            field=models.CharField(blank=True, max_length=200, verbose_name='Издатель игры'),
        ),
        migrations.AddField(
            model_name='article',
            name='game_release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выхода игры'),
        ),
        migrations.AddField(
            model_name='article',
            name='game_store_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на магазин'),
        ),
        migrations.AddField(
            model_name='article',
            name='system_requirements',
            field=models.TextField(blank=True, verbose_name='Системные требования'),
        ),
    ]
