# Generated by Django 5.2.7 on 2025-11-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_game_developer_article_game_platforms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='color',
            field=models.CharField(default='#A9A9A9', help_text='В формате HEX, например: #805AD5', max_length=7, verbose_name='Цвет жанра'),
        ),
    ]
