# Generated by Django 5.2.7 on 2025-11-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_genre_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='genre',
        ),
        migrations.AddField(
            model_name='article',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='articles', to='news.genre', verbose_name='Жанры игры'),
        ),
    ]
