# Generated by Django 5.2.7 on 2025-11-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_article_genre_article_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('list', 'Список'), ('quote', 'Цитата'), ('warning', 'Предупреждение'), ('info', 'Информация')], max_length=10, verbose_name='Тип блока'),
        ),
    ]
