# Generated by Django 5.2.7 on 2025-11-21 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_articleblock_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_game',
            field=models.ForeignKey(blank=True, help_text='Выберите игру, если статья/новость о ней', limit_choices_to={'category__slug': 'igry'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.article', verbose_name='Связанная игра'),
        ),
    ]
